version: '3.6'
services:
  graphql-engine:
    volumes:
      - ./migrations:/hasura-migrations
    image: hasura/graphql-engine:v1.0.0-rc.1.cli-migrations
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura-migrations
      HASURA_GRAPHQL_DATABASE_URL:
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false" # set to "false" to disable console
      HASURA_GRAPHQL_ADMIN_SECRET:
volumes:
  db_data:
